name: Actualització Radar Meteocat

on:
  workflow_dispatch: # Execució manual
  schedule:
    - cron: '*/6 * * * *' # Execució cada 6 minuts (si vols activar-ho ja)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instal·lar dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de descàrrega
        run: python radar_to_nc.py

      # En lloc de fer Push, pugem el fitxer .nc a Artifacts
      - name: Guardar radar com artifact
        uses: actions/upload-artifact@v4
        with:
          # Fem servir un nom d'artifact que inclogui el dia
          # Això permetrà que el workflow diari els trobi tots junts
          name: radars-temporals
          path: dades_radar/*.nc
          retention-days: 1 # Mantenim el mínim de temps possible (24h)

      - name: Commit i Push dels canvis
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
